config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      get 'orders/index'
    end
  end

  namespace :api do
    namespace :v1 do
      get 'orders/show'
    end
  end

  get '/', to: 'welcome#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/dashboard', to: 'users#show'
  get '/logout', to: 'sessions#destroy'

  # root to: "welcome#index"
  post '/cart', to: 'cart#create', as: 'cart_index'
  get '/cart', to: 'cart#show', as: 'cart'
  patch '/cart', to: 'cart#update'
  #get '/:id', to: 'categories#show'
  delete '/cart', to: 'cart#destroy'
   #resources :cart, only: [:create]

  #resources :freelancers, only: [:show]
  get '/freelancers', to: 'freelancers#index'
  get '/freelancers/:id', to: 'freelancers#show', as: 'freelancer'
  get '/categories', to: 'categories#index'
  get '/:id', to: 'categories#show', as: 'category'

  #resources :categories, only: [ :show]
  get '/users/new', to: 'users#new', as: 'new_user'
  post '/users', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/orders', to: 'orders#index'
  get '/orders', to: 'orders#show', as: 'order'
  post '/orders', to: 'order#create'
  #resources :users, only: [:new, :create, :show]
  #resources :orders, only: [:index, :show, :create]

  get '/admin/users/:id', to: 'admin/users#show', as: 'admin_user'
  put '/admin/users/:id', to: 'admin/users#update'
  patch '/admin/users/:id', to: 'admin/users#update'
  get '/admin/users/:id/edit', to: 'admin/users#edit', as: 'edit_admin_user'

  get '/admin/freelancers', to: 'admin/freelancers#index', as: 'admin_freelancers'
  post '/admin/freelancers', to: 'admin/freelancers#create'
  get '/admin/freelancers/new', to:'admin/freelancers#new', as: 'new_admin_freelancer'
  get '/admin/freelancers/:id/edit', to: 'admin/freelancers#edit', as: 'edit_admin_freelancer'
  patch '/admin/freelancers/:id', to: 'admin/freelancers#update'
  put '/admin/freelancers/:id', to: 'admin/freelancers#update'
  get '/admin/orders/:id', to: 'admin/orders#show', as: 'admin_order'
  get 'admin/dashboard', to: 'admin/orders#index', as: 'admin_dashboard'
  patch 'admin/dashboard', to: 'admin/orders#update'

  # namespace :admin do
  #   resources :users, only: [:edit, :update, :show]
  #   resources :freelancers, only: [:new, :create, :index, :edit, :update]

    #resources :orders, only: [:show]

end

app/models/cart.rb
class Cart
  attr_reader :contents

  def initialize(cart_info)
    @contents = cart_info || {}
  end

  def total_count
    contents.values.sum
  end

  def count_of(id)
    contents[id.to_s] || 0
  end

  def add_freelancer(id)
    contents[id.to_s] = (contents[id.to_s] || 0) + 1
  end

  def delete_freelancer(id)
    contents[id.to_s] = 0
    contents.delete(id.to_s)
  end

  def decrease_freelancer(id)
    contents[id.to_s] = contents[id.to_s] - 1
    delete_freelancer(id) if contents[id.to_s] == 0
  end

  def freelancer_ids
    contents.keys
  end

  def collect_freelancers
    Freelancer.where(id: freelancer_ids)
  end

  def subtotal(freelancer)
    count_of(freelancer.id) * freelancer.price
  end

  def total_price
    collect_freelancers.reduce(0) do |sum, freelancer|
      sum + (freelancer.price * count_of(freelancer.id))
    end
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  include ActionView::Helpers::TextHelper

  def show
  end

  def create
    freelancer = Freelancer.find(params[:freelancer_id])

    @cart.add_freelancer(freelancer.id)
    session[:cart] = @cart.contents

    flash[:info] = "You now have #{pluralize(@cart.count_of(freelancer.id), 'hour')} of #{freelancer.name}'s time in your cart."
    redirect_to request.referer
  end

  def destroy
    freelancer = Freelancer.find(params[:freelancer_id])

    @cart.delete_freelancer(freelancer.id)
    session[:cart] = @cart.contents

    flash[:success] = "Successfully removed #{view_context.link_to "#{freelancer.name}", freelancer_path(freelancer), class: 'alert-link'} from your cart."
    redirect_to cart_path
  end

  def update
    freelancer = Freelancer.find(params[:freelancer_id])

    @cart.decrease_freelancer(freelancer.id)
    session[:cart] = @cart.contents
    redirect_to cart_path
  end

end

app/views/cart/show.html.erb
<h1>Current Cart</h1>

<div class="total-price-cart">
    <h3>Total: $<%= @cart.total_price %></h3>
    <% if current_user.nil? %>
  <div class="login-to-checkout">
    <%= link_to "Login or Create Account to Checkout", login_path %>
  </div>
    <% else %>
  <div class="checkout">
    <%= button_to "Checkout", orders_path(cart_contents: @cart.contents), class: 'btn btn-primary' %>
  </div>
    <% end %>
</div>

  <% @cart.collect_freelancers.each do |freelancer| %>
    <div class="row" id="item">
      <div class="col-sm-4">
        <%= link_to freelancer_path(freelancer) do %>
          <%=image_tag(freelancer.image, size: "150x150", class: "image-fl-index", id: "image_#{freelancer.id}") %>
        <% end %>
      <h4>Name: <%= freelancer.name %></h4>
      <p> <%= freelancer.description %></p>
      </div>
      <div class="col-sm-4 d-flex justify-content-around">
        <div class="d-flex flex-column justify-content-around">
        <h4> Quantity: <%= @cart.count_of(freelancer.id)%></h4>
          <%= button_to "Increase Amount", cart_index_path(freelancer_id: freelancer.id), class: "btn btn-info"%>
          <%= button_to "Decrease Amount", cart_path(freelancer_id: freelancer.id), class: "btn btn-info", method: :patch%>
        </div>
      </div>
        <div class="col-sm-4 d-flex justify-content-around">
          <div class="d-flex flex-column justify-content-around">
          <h5> $<%= freelancer.price %>/hr</h5>
          <h4>  Subtotal: $<%= @cart.subtotal(freelancer) %></h4>
          <%= button_to "Remove #{freelancer.name}'s time from your cart.", cart_index_path(freelancer_id: freelancer.id), class: "btn btn-danger", method: :delete %>
        </div>
      </div>
    </div>
      <% end %>
    </div>

</div>