config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      get 'orders/index'
    end
  end

  namespace :api do
    namespace :v1 do
      get 'orders/show'
    end
  end

  get '/', to: 'welcome#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/dashboard', to: 'users#show'
  get '/logout', to: 'sessions#destroy'

  # root to: "welcome#index"
  post '/cart', to: 'cart#create', as: 'cart_index'
  get '/cart', to: 'cart#show', as: 'cart'
  patch '/cart', to: 'cart#update'
  #get '/:id', to: 'categories#show'
  delete '/cart', to: 'cart#destroy'
   #resources :cart, only: [:create]

  #resources :freelancers, only: [:show]
  get '/freelancers', to: 'freelancers#index'
  get '/freelancers/:id', to: 'freelancers#show', as: 'freelancer'
  get '/categories', to: 'categories#index'
  get '/:id', to: 'categories#show', as: 'category'

  #resources :categories, only: [ :show]
  get '/users/new', to: 'users#new', as: 'new_user'
  post '/users', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/orders', to: 'orders#index'
  get '/orders', to: 'orders#show', as: 'order'
  post '/orders', to: 'order#create'
  #resources :users, only: [:new, :create, :show]
  #resources :orders, only: [:index, :show, :create]

  get '/admin/users/:id', to: 'admin/users#show', as: 'admin_user'
  put '/admin/users/:id', to: 'admin/users#update'
  patch '/admin/users/:id', to: 'admin/users#update'
  get '/admin/users/:id/edit', to: 'admin/users#edit', as: 'edit_admin_user'

  get '/admin/freelancers', to: 'admin/freelancers#index', as: 'admin_freelancers'
  post '/admin/freelancers', to: 'admin/freelancers#create'
  get '/admin/freelancers/new', to:'admin/freelancers#new', as: 'new_admin_freelancer'
  get '/admin/freelancers/:id/edit', to: 'admin/freelancers#edit', as: 'edit_admin_freelancer'
  patch '/admin/freelancers/:id', to: 'admin/freelancers#update'
  put '/admin/freelancers/:id', to: 'admin/freelancers#update'
  get '/admin/orders/:id', to: 'admin/orders#show', as: 'admin_order'
  get 'admin/dashboard', to: 'admin/orders#index', as: 'admin_dashboard'
  patch 'admin/dashboard', to: 'admin/orders#update'

  # namespace :admin do
  #   resources :users, only: [:edit, :update, :show]
  #   resources :freelancers, only: [:new, :create, :index, :edit, :update]

    #resources :orders, only: [:show]

end

app/models/freelancer.rb
class Freelancer < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  belongs_to :category
  has_many :order_freelancers
  has_many :orders, through: :order_freelancers

  enum status: ["active", "retired"]
end

app/controllers/admin/freelancers_controller.rb
class Admin::FreelancersController < Admin::BaseController

  def index
    @freelancers = Freelancer.all
  end

  def new
    @freelancer = Freelancer.new
  end

  def create

    @category= Category.find_by(title: category_params[:category])
    @freelancer = @category.freelancers.new(freelancer_params)
    # Set freelancer.image equal to the params[:avatar] and save the post.
    if @freelancer.save

      flash[:success] = "You succefully created #{@freelancer.name}"
      redirect_to freelancer_path(@freelancer)
    else
      render :new
      flash[:danger] = "Try again! Information is wrong."
    end
  end

  private

  def freelancer_params
    params.require(:freelancer).permit(:name, :description, :price, :avatar)
  end

  def category_params
    params.require(:freelancer).permit(:category)
  end

end

app/controllers/freelancers_controller.rb
class FreelancersController < ApplicationController

  def index
    @freelancers = Freelancer.all
  end

  def show
    @freelancer = Freelancer.find(params[:id])
  end

end

app/views/admin/freelancers/_form.html.erb
<div class="form-container">
<div class="form-outline">
  <%=form_for [:admin, @freelancer] do |f| %>
  <div class="new-account-item">
    <div class="form-control account-input">
      <%= f.label :name, class: 'new-account-label'%>
      <%= f.text_field :name, class: 'new-account-box'%>
    </div>
  </div>

  <div class="new-account-item">
    <div class="form-control account-input">
      <%= f.label :description, class: 'new-account-label'%>
      <%= f.text_area :description, class: 'new-account-box'%>
    </div>
  </div>

  <div class="new-account-item">
    <div class="form-control account-input">
      <%= f.label :price, as: :currency, class: 'new-account-label'%>
      <%= f.text_field :price, class: 'new-account-box'%>
    </div>
  </div>

  <div class="new-account-item">
    <div class="form-control account-input">
      <%= f.label :category, class: 'new-account-label'%>
      <%= f.select :category, Category.all.pluck(:title) %>
    </div>
  </div>

  <div class="new-account-item">
    <div class="form-control account-input">
      <%= f.label :status, class: 'new-account-label'%>
        <%= f.select :status, ['active', 'retired'] %>
    </div>
  </div>


  <div class="new-account-item">
    <%= f.submit "Submit", class: "btn btn-primary create-button" %>
  </div>
  <% end %>
</div>
</div>
</div>

app/views/admin/freelancers/edit.html.erb
<h1>Edit <%= @freelancer.name %> here!</h1>

<%= render partial: "form" %>

app/views/admin/freelancers/index.html.erb
<h1>Browse our Techies  </h1>
 <div>
   <%= link_to "Add a New Freelancer", new_admin_freelancer_path, class: "nav-link" %>
 </div>


<div class="card-container">
  <% @freelancers.each do |freelancer| %>
  <div class="card-show">
    <%= link_to freelancer_path(freelancer) do %>
    <%= image_tag("#{freelancer.image}", alt: "photo of #{freelancer.name}", class: "card-img-top card-image") %>
    <% end %>
    <h4 class="card-title"> <%=freelancer.name%></h4>
    <p class="card-text card-description"><%=freelancer.description%></p>
    <p class="card-text"><%=number_to_currency(freelancer.price)%>/hr</p>
    <p class="card-text"><%=freelancer.status%></p>
    <div class="card-show-button">
      <h5 class='card-show-link'><%= link_to "Edit", edit_admin_freelancer_path(freelancer)%></h5>
      <% if freelancer.active? %>
      <%= button_to "Choose Me!", cart_index_path(freelancer_id: freelancer.id), class: "btn btn-primary"%>
      <% else %>
      <p> Freelancer Retired </p>
      <% end %>
    </div>
  </div>
  <% end %>
</div>

app/views/admin/freelancers/new.html.erb
<h1>Create a new Freelancer here!</h1>

<div class="form-container">
  <%= render partial: "form" %>
</div>