config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      get 'orders/index'
    end
  end

  namespace :api do
    namespace :v1 do
      get 'orders/show'
    end
  end

  get '/', to: 'welcome#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/dashboard', to: 'users#show'
  get '/logout', to: 'sessions#destroy'

  # root to: "welcome#index"
  post '/cart', to: 'cart#create', as: 'cart_index'
  get '/cart', to: 'cart#show', as: 'cart'
  patch '/cart', to: 'cart#update'
  #get '/:id', to: 'categories#show'
  delete '/cart', to: 'cart#destroy'
   #resources :cart, only: [:create]

  #resources :freelancers, only: [:show]
  get '/freelancers', to: 'freelancers#index'
  get '/freelancers/:id', to: 'freelancers#show', as: 'freelancer'
  get '/categories', to: 'categories#index'
  get '/:id', to: 'categories#show', as: 'category'

  #resources :categories, only: [ :show]
  get '/users/new', to: 'users#new', as: 'new_user'
  post '/users', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/orders', to: 'orders#index'
  get '/orders', to: 'orders#show', as: 'order'
  post '/orders', to: 'order#create'
  #resources :users, only: [:new, :create, :show]
  #resources :orders, only: [:index, :show, :create]

  get '/admin/users/:id', to: 'admin/users#show', as: 'admin_user'
  put '/admin/users/:id', to: 'admin/users#update'
  patch '/admin/users/:id', to: 'admin/users#update'
  get '/admin/users/:id/edit', to: 'admin/users#edit', as: 'edit_admin_user'

  get '/admin/freelancers', to: 'admin/freelancers#index', as: 'admin_freelancers'
  post '/admin/freelancers', to: 'admin/freelancers#create'
  get '/admin/freelancers/new', to:'admin/freelancers#new', as: 'new_admin_freelancer'
  get '/admin/freelancers/:id/edit', to: 'admin/freelancers#edit', as: 'edit_admin_freelancer'
  patch '/admin/freelancers/:id', to: 'admin/freelancers#update'
  put '/admin/freelancers/:id', to: 'admin/freelancers#update'
  get '/admin/orders/:id', to: 'admin/orders#show', as: 'admin_order'
  get 'admin/dashboard', to: 'admin/orders#index', as: 'admin_dashboard'
  patch 'admin/dashboard', to: 'admin/orders#update'

  # namespace :admin do
  #   resources :users, only: [:edit, :update, :show]
  #   resources :freelancers, only: [:new, :create, :index, :edit, :update]

    #resources :orders, only: [:show]

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_freelancers
  has_many :freelancers, through: :order_freelancers

  enum status: ["Ordered", "Paid", "Cancelled", "Completed"]

  def grouped_freelancers
    freelancers.group(:id).count
  end

  def subtotal(id, quantity)
    quantity * freelancers.find(id).price
  end

  def total
    grouped_freelancers.map do |id, quantity|
      quantity * freelancers.find(id).price
    end.sum
  end

  def create_orders(cart_contents)
    cart_contents.each do |freelancer_id, quantity|
      freelancer = Freelancer.find(freelancer_id.to_i)
      quantity.to_i.times do
        self.freelancers << freelancer
      end
    end
  end


  def self.total_ordered
    where(status: 0).count
  end

  def self.total_paid
    where(status: 1).count
  end

  def self.total_cancelled
    where(status: 2).count
  end

  def self.total_completed
    where(status: 3).count
  end

  def self.filter_by(status_params)
    where(status: status_params)
  end

  def self.orders_by_id
    order(:id)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController

  def index
    @all_orders = Order.all
    if params[:filter_by]
      @orders = Order.filter_by(params[:filter_by])
    else
      @orders = Order.orders_by_id
    end
  end


  def show
    @order = Order.find(params[:id])
    @freelancers = @order.freelancers
  end


  def update
    order = Order.find(params[:order_id])
    order.update(status: params[:status])
    redirect_to admin_dashboard_path
  end


end

app/controllers/api/v1/orders_controller.rb
class Api::V1::OrdersController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @user = current_user
  end

  def show
    if current_user.id != Order.find(params[:id]).user_id
      render file: "public/404"
    else
      @order = current_user.orders.find(params[:id])
      @freelancers = @order.freelancers
    end
  end

  def create
    @user = current_user
    order = @user.orders.create
    order.create_orders(params[:cart_contents])
    flash[:success] = "Order was successfully placed!"
    session[:cart].clear
    redirect_to orders_path
  end

end

app/helpers/api/v1/orders_helper.rb
module Api::V1::OrdersHelper
end

app/views/admin/orders/index.html.erb
<h1>Admin Dashboard</h1>

<div id="admin-dash-header">
  <h4>Orders by Status</h4>
  <span class="total">Ordered: <%= @all_orders.total_ordered %></span>
  <span class="total">Paid: <%= @all_orders.total_paid %></span>
  <span class="total">Completed: <%= @all_orders.total_completed %></span>
  <span class="total">Cancelled: <%= @all_orders.total_cancelled %></span>
</div>

<div id="filter_by">
  <h4>Filter by</h4>
  <div class="link"><%= link_to "Ordered", admin_dashboard_path(filter_by: 0) %></div>
  <div class="link"><%= link_to "Paid", admin_dashboard_path(filter_by: 1) %></div>
  <div class="link"><%= link_to "Cancelled", admin_dashboard_path(filter_by: 2) %></div>
  <div class="link"><%= link_to "Completed", admin_dashboard_path(filter_by: 3) %></div>
  <div class="link"><%= link_to "All", admin_dashboard_path %></div>
</div>

      <div class='filtered-orders' id="order-table">
        <table class="table table-striped">
            <thead>
              <tr>
                <th>
                  Order Id
                </th>
                <th>
                  Status
                </th>
                <th>
                  Action
                </th>
                <th>
                  View Order
                </th>
              </tr>
            </thead>
              <% @orders.each do |order| %>
              <tr class="order-<%="#{order.id}"%>">
                <td>
                  <%= order.id %>
                </td>
                <td>
                  <%=order.status %>
                </td>
                <td>
                  <% if order.status == ("Ordered" || "Paid") %>
                  <%= link_to "Cancel", admin_dashboard_path(order_id: order.id, status: 'Cancelled'), method: :patch %>
                  <% end %>
                  <% if order.Ordered? %>
                  <%= link_to "Mark as Paid", admin_dashboard_path(order_id: order.id, status: 'Paid'), method: :patch %>

                  <% end %>
                  <% if order.Paid? %>
                  <%= link_to "Mark as Completed", admin_dashboard_path(order_id: order.id, status: 'Completed'), method: :patch %>
                  <% end %>
                </td>
                <td>
                  <%= link_to "View Order #{order.id}", admin_order_path(order) %>
                </td>
              </tr>
              <%end %>
            </tbody>
          </table>
        </div>

app/views/admin/orders/show.html.erb
<h1>Order: <%=@order.id%></h1>

<div class="user-info">
  <h5> Purchaser: <%= @order.user.full_name %></h5>
  <div> Date: <%= @order.created_at.strftime(format='%m/%d/%Y: %H:%M:%S %Z') %></div>
  <div> Company:<%= @order.user.company%></div>
  <div> Address:<%= @order.user.address1%></div>
  <div><%= @order.user.address2%></div>
  <div> City:<%= @order.user.city%></div>
  <div> State:<%= @order.user.state%></div>
  <div> Zip:<%= @order.user.zip%></div>

  <div>Status: <%= @order.status %></div>
  <% if @order.status == ("Completed" || "Cancelled") %>
  <div>Updated on: <%= @order.updated_at %><%end%></div>
</div>

<div id="order-show-table">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>
          Name
        </th>
        <th>
          Quantity
        </th>
        <th>
          Price
        </th>
        <th>
          Subtotal
        </th>
        <th>
          Freelance Details
        </th>
      </tr>
    </thead>
    <tbody>
      <% @order.grouped_freelancers.each do |id, quantity| %>
      <tr>
        <td>
          <%= @freelancers.find(id).name %>
        </td>
        <td>
          <%= pluralize(quantity, 'hour') %>
        </td>
        <td>
          <%= number_to_currency(@freelancers.find(id).price) %>
        </td>
        <td>
          <%= number_to_currency(@order.subtotal(id, quantity)) %>
        </td>
        <td>
          <%= link_to "View Freelancer", freelancer_path(@freelancers.find(id)) %>
        </td>
      </tr>
      <%end%>
    </tbody>
  </table>
</div>

<div class="order-show-total">Total: <%= number_to_currency(@order.total) %></div>