config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      get 'orders/index'
    end
  end

  namespace :api do
    namespace :v1 do
      get 'orders/show'
    end
  end

  get '/', to: 'welcome#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/dashboard', to: 'users#show'
  get '/logout', to: 'sessions#destroy'

  # root to: "welcome#index"
  post '/cart', to: 'cart#create', as: 'cart_index'
  get '/cart', to: 'cart#show', as: 'cart'
  patch '/cart', to: 'cart#update'
  #get '/:id', to: 'categories#show'
  delete '/cart', to: 'cart#destroy'
   #resources :cart, only: [:create]

  #resources :freelancers, only: [:show]
  get '/freelancers', to: 'freelancers#index'
  get '/freelancers/:id', to: 'freelancers#show', as: 'freelancer'
  get '/categories', to: 'categories#index'
  get '/:id', to: 'categories#show', as: 'category'

  #resources :categories, only: [ :show]
  get '/users/new', to: 'users#new', as: 'new_user'
  post '/users', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/orders', to: 'orders#index'
  get '/orders', to: 'orders#show', as: 'order'
  post '/orders', to: 'order#create'
  #resources :users, only: [:new, :create, :show]
  #resources :orders, only: [:index, :show, :create]

  get '/admin/users/:id', to: 'admin/users#show', as: 'admin_user'
  put '/admin/users/:id', to: 'admin/users#update'
  patch '/admin/users/:id', to: 'admin/users#update'
  get '/admin/users/:id/edit', to: 'admin/users#edit', as: 'edit_admin_user'

  get '/admin/freelancers', to: 'admin/freelancers#index', as: 'admin_freelancers'
  post '/admin/freelancers', to: 'admin/freelancers#create'
  get '/admin/freelancers/new', to:'admin/freelancers#new', as: 'new_admin_freelancer'
  get '/admin/freelancers/:id/edit', to: 'admin/freelancers#edit', as: 'edit_admin_freelancer'
  patch '/admin/freelancers/:id', to: 'admin/freelancers#update'
  put '/admin/freelancers/:id', to: 'admin/freelancers#update'
  get '/admin/orders/:id', to: 'admin/orders#show', as: 'admin_order'
  get 'admin/dashboard', to: 'admin/orders#index', as: 'admin_dashboard'
  patch 'admin/dashboard', to: 'admin/orders#update'

  # namespace :admin do
  #   resources :users, only: [:edit, :update, :show]
  #   resources :freelancers, only: [:new, :create, :index, :edit, :update]

    #resources :orders, only: [:show]

end

app/models/category.rb
class Category < ApplicationRecord

  validates :title, presence: true
  has_many :freelancers

  before_save :generate_slug

  def generate_slug
    self.slug = title.parameterize
  end  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.find_by(slug: params[:id])
  end

  def index
    @categories = Category.all
  end
end

app/views/categories/index.html.erb
<h2>TechTime connects you with talented techies with these specialties:</h2>

<div class="card-outer-container">
  <div class="card-container">
    <% @categories.each do |category| %>
      <div class="card-category">
        <%= link_to category.title, category_path(category.slug), class: 'category-link' %>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/show.html.erb
<h1><%=@category.title %></h1>

<div class="card-container">
  <% @category.freelancers.each do |freelancer| %>
  <div class="card-show">
    <%= link_to freelancer_path(freelancer) do %>
    <%= image_tag("#{freelancer.image}", alt: "photo of #{freelancer.name}", class: "card-img-top card-image") %>
    <% end %>
    <h4 class="card-title"> <%=freelancer.name%></h4>
    <p class="card-text card-description"><%=freelancer.description%></p>
    <p class="card-text"><%=number_to_currency(freelancer.price)%>/hr</p>
    <div class="card-show-button">
      <% if freelancer.active? %>
      <%= button_to "Choose Me!", cart_index_path(freelancer_id: freelancer.id), class: "btn btn-primary"%>
      <% else %>
      <p> Freelancer Retired </p>
      <% end %>
    </div>
  </div>
  <% end %>
</div>